title: 巧克力的小簿子
author: 巧克力啊
description: echo
url : "https://note.qiaokelia.xyz" 

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

highlighter: rouge

include:
  - _pages

paginate:  10 

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md 

plugins:
  - jekyll-archives
  - jekyll-paginate

jekyll-archives:
  enabled:
    - year
    - tags
  layout: archives
  permalinks:
    year: '/archives/:year/'
    tag: '/archives/tag/:name/'

weather:
  晴: 'sun'
  多云: 'cloud-sun'
  阴: 'cloud'
  小雨: 'umbrella'
  大雨: 'cloud-showers-heavy'
  雪: 'snowflake'
  雾: 'smog'